# Generated by Django 6.0.2 on 2026-03-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Поддержка HTML')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('acrylic_powder', 'Акриловая пудра'), ('gel', 'Гель'), ('modeling_gel', 'Гель для моделирования ногтей'), ('gel_paint', 'Гель-краска для ногтей'), ('gel_lacquer', 'Гель-лак'), ('decor', 'Декор для маникюра'), ('top_coat', 'Закрепитель для гель-лака'), ('tools', 'Инструмент для маникюра и Педикюра'), ('brushes', 'Кисть для дизайна ногтей'), ('nail_glue', 'Клей для ногтей'), ('corrector', 'Корректор'), ('uv_lamp', 'Лампа для сушки ногтей'), ('magnet', 'Магнит для маникюра'), ('manicure_set', 'Маникюрный набор'), ('cosmetic_soap', 'Мыло косметическое'), ('press_on_nails', 'Накладные ногти'), ('false_eyelashes', 'Накладные ресницы'), ('base_gel_lacquer', 'Основа под гель-лак'), ('base_lacquer', 'Основа под лак'), ('nail_file', 'Пилка для ногтей'), ('mascara', 'Тушь'), ('cosmetic_brush', 'Щетка косметическая')], max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maingb.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('default_address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingb.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
