# Generated by Django 6.0.2 on 2026-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Поддержка HTML (например, &lt;br&gt;, &lt;strong&gt;)'),
        ),
    ]
